### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by Mikey2055** [imvast/Capmonster-Checker#1]
Add threads to the checker

**Comment by ledges** [comment]
> Add threads to the checker

do it yourself xD

**Comment by imvast** [comment]
I actually made an asynchronous version but it ended up fucking over the capmonster api causing connections to the site resulting unsuccessfully.

**Comment by ledges** [comment]
> I actually made an asynchronous (threaded) version but it ended up fucking over the capmonster api causing connections to the site resulting unsuccessfully.

seriously.
