### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Alaneczek123123851** [imvast/Capmonster-Checker#4]
py main.py
[*] Starting checker with 100000 keys...
[ERROR] Exception in checker -> Expecting value: line 1 column 1 (char 0)

**Comment by jprocks101** [comment]
rate limit

**Comment by LiteEagle262** [comment]
u can use residential proxies and add that but capsmonster blocks reg proxies

**Comment by imvast** [comment]
ratelimit. ill update in a week 👍
