### ISSUE TITLE
Retarded program

### ISSUE THREAD

**Issue by ercenterprises** [imvast/Capmonster-Checker#6]
It would take `2.909097186765047e+28` years to crack a capmonster key 🤣

**Comment by imvast** [comment]
🤷 i made it for fun and it can be improved but i just dont feel like it 💀

**Comment by imvast** [comment]
> "Made it for fun" just say you're a skid, stop chirping lil bro

🤡 alr son go learn what skidding really is ignorant goofball

**Comment by imvast** [comment]
> so if you're not a skid, why make this?

what does this program have anything to do with being a skid? 💀 
i literally made it because one of my friends suggested i make it for him and decided to publish it cuz why not?

**Comment by imvast** [comment]
> > so if you're not a skid, why make this?
> 
> what does this program have anything to do with being a skid? 💀 i literally made it because one of my friends suggested i make it for him and decided to publish it cuz why not?

+ on top of that this shit took me maybe 5 minutes to do and i couldnt care less about how good it is
~ obviously its going to have a super low chance of getting a key but so what you were obviously looking for this program or else you wouldnt be on it 🤡

**Comment by imvast** [comment]
> Go isn't even in your "know languages" section on your readme so nvm, you are a skid 🤣

actually it is and again that has nothing to do with anything 🤡

**Comment by imvast** [comment]
> Buddy you literally failed math, there's no "super low" chance, it's literally next to impossible.
> 
> Plus this didn't take you 5m to make otherwise you wouldn't have to switch between languages 🤡
> 
> You probably asked (ahem. ChatGPT) to write you the code..
> 
> You're literally in the https://skid.wiki too 🤣

math also has nothing to do with chances 💀 you are sped asf and again what does switching langs have to do with anything at all. i made the key gen in golang cuz go does that shit fast 🤡

**Comment by imvast** [comment]
@eric48906 ur honestly sped asf idek what to tell you like you have no chance of success in life
