### ISSUE TITLE
Retard

### ISSUE THREAD

**Issue by eric48906** [imvast/Capmonster-Checker#7]
"mAtH hAs NoThInG tO dO wItH cHaNcHEs"

- Dropped out of high school to make skidded programs
You're on the https://skid.wiki for a reason lil bro 🤣 
Obviously I know Golang is faster, but thats all you know about go since you used chatgpt to write it 😂

**Comment by imvast** [comment]
> "mAtH hAs NoThInG tO dO wItH cHaNcHEs"
> 
> * Dropped out of high school to make skidded programs
>   You're on the https://skid.wiki for a reason lil bro 🤣
>   Obviously I know Golang is faster, but thats all you know about go since you used chatgpt to write it 😂

🥱 u love riding my dick dont u son
skid.wiki is irrelevant asf and he put me on there cuz hes got a grudge LOL
show proof of me using chatgpt for the keygen its basic asf so whats the point dumb fuck
dont get mad that you cant code for shit and need attention on github 💀 
* also false claims i didnt drop out of school unlike u whos definitely failing the 7th grade dumbass dimwitted 12yr old 🤡
