### ISSUE TITLE
Skid

### ISSUE THREAD

**Issue by eric48906** [imvast/Capmonster-Checker#8]
im fucking retarded   - eric cartman 2023

**Comment by Tukzlol** [comment]
> Can't even add threads, skid 🥱

learn how to read

**Comment by imvast** [comment]
@eric48906 holy shit u love my dick like keep riding it plss 
i literally did add threads before and theres no point because of ratelimit n shit 🤯

**Comment by imvast** [comment]
> Forgot to mention this "tukz" kid is following 48 people and has 8 followers (probably alts) 🤣
> Average script kidde behavior! 😂 😂

not an alt but he doesnt code much but its alr u stay having a threesome and riding us 😘

**Comment by imvast** [comment]
> > ```
> >           I actually made an asynchronous (threaded) version but it ended up fucking over the capmonster api causing connections to the site resulting unsuccessfully.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _Originally posted by @imvast in [#1 (comment)](https://github.com/imvast/Capmonster-Checker/issues/1#issuecomment-1420042643)_
> > I wonder why skid 🤣
> 
> 
> maybe use ur brain ? it fucks their whole api no matter proxy or not 🤡

cuz their api = 💩

**Comment by imvast** [comment]
> Bro really says he knows a markdown language in his readme 😭 Skid moments 2023 💯

🤦 u have some brain damage cuz theres no where in my readme about knowing md

**Comment by imvast** [comment]
> > ur prolly an irl **eric** cartman
> 
> You're* (how many times do I need to remind you skid)
> 
> You probably look like this ![image](https://user-images.githubusercontent.com/64490610/221677105-79f30bf7-462f-40c1-950a-6901498cce63.png)

🤡 dont send ur selfies on my github

**Comment by imvast** [comment]
> > > > ur prolly an irl **eric** cartman
> > > 
> > > 
> > > You're* (how many times do I need to remind you skid)
> > > You probably look like this ![image](https://user-images.githubusercontent.com/64490610/221677105-79f30bf7-462f-40c1-950a-6901498cce63.png)
> > 
> > 
> > 🤡 dont send ur selfies on my github
> 
> selfies? are you dumb LOL 😂 That's not a selfie & that's you, cry harder bozo

🥱 goofball thats a pic of you 🤡
